#!/bin/sh
cd "${0%/*}" || exit                                # Run from this directory
. ${WM_PROJECT_DIR:?}/bin/tools/RunFunctions        # Tutorial run functions
#------------------------------------------------------------------------------

runApplication blockMesh
runApplication transformPoints -scale "(1 0 1)"
runApplication extrudeMesh

decomposePar
mpirun -np 8 rhoPimpleFoam -parallel
reconstructPar

rhoPimpleFoam -postProcess -func yPlus > yPlus.log
rhoPimpleFoam -postProcess -func wallShearStress > wallShearStress.log
rhoPimpleFoam -postProcess -func sampleUpperPwall
rhoPimpleFoam -postProcess -func sampleLowerPwall
#------------------------------------------------------------------------------
