#!/bin/sh
blockMesh
transformPoints -scale "(1 0 1)"
extrudeMesh

decomposePar
mpirun -np 8 --allow-run-as-root rhoPimpleFoam -parallel
reconstructPar

rhoPimpleFoam -postProcess -func yPlus > yPlus.log
rhoPimpleFoam -postProcess -func wallShearStress > wallShearStress.log
rhoPimpleFoam -postProcess -func sampleUpperPwall
rhoPimpleFoam -postProcess -func sampleLowerPwall
#------------------------------------------------------------------------------
